import type { Metadata } from "next";
import { Cormorant_Garamond, Poppins } from "next/font/google";
import "./globals.css";

const cormorantGaramond = Cormorant_Garamond({
  subsets: ["latin"],
  variable: "--font-cormorant-garamond",
  weight: ["400"],
});

const poppins = Poppins({
  subsets: ["latin"],
  variable: "--font-poppins",
  weight: ["400", "600"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${cormorantGaramond.variable} ${poppins.variable} bg-gradient-to-r from-blue-400 to-blue-200 min-h-screen flex flex-col`}
      >
        <header className="bg-gradient-to-r from-blue-400 to-blue-200 shadow-lg p-4 flex justify-between items-center">
          <h1 className="text-2xl font-bold text-white">Patrick's First NEXTJS blog</h1>
          <nav>
            <ul className="flex space-x-4">
              <li><a href="#" className="text-black hover:text-blue-200 transition-colors">Home</a></li>
              <li><a href="#" className="text-black hover:text-blue-200 transition-colors">About</a></li>
              <li><a href="#" className="text-black hover:text-blue-200 transition-colors">Contact</a></li>
            </ul>
          </nav>
        </header>
        
        <main className="flex-grow container mx-auto p-6">
          {children}
        </main>
        
        <footer className="bg-gradient-to-r from-blue-400 to-blue-200 shadow-lg p-4 text-center">
          <p className="text-white">&copy; 2024 My Next App. All rights reserved.</p>
        </footer>
      </body>
    </html>
  );
}
